[package]
name = "qn"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
quinn = "0.11.9"
quinn-proto = "0.11.13"
tokio = {version = "1.49.0", features = ["full"]}
anyhow = "1.0.100"
quinn-plaintext = "0.3.0"
